Repository rossvideo/Catena, pull requests merged in 2024-08, with the labels that each got.

#227 Docker workspace
  .vscode/.devcontainer/devcontainer.json
  sdks/cpp/docker/build.sh
  sdks/cpp/docker/dev-start.sh
  sdks/cpp/docker/dockerfiles/Dockerfile.base
  sdks/cpp/docker/dockerfiles/Dockerfile.codeql
  sdks/cpp/docker/dockerfiles/Dockerfile.develop
  sdks/cpp/docker/dockerfiles/Dockerfile.toolchain
  sdks/cpp/docs/docker-cpp.md
Labels: documentation, enhancement

#225 Constraint device support added
  sdks/cpp/common/include/IConstraint.h
  sdks/cpp/connections/gRPC/examples/status_update/device.status_update.json
  sdks/cpp/connections/gRPC/examples/status_update/static/status_update.grid
  sdks/cpp/connections/gRPC/examples/status_update/status_update.cpp
  sdks/cpp/connections/gRPC/src/ServiceImpl.cpp
  sdks/cpp/lite/examples/start_here/device.start_here.json
  sdks/cpp/lite/include/IConstraint.h
  sdks/cpp/lite/include/IParam.h
  sdks/cpp/lite/include/NamedChoiceConstraint.h
  sdks/cpp/lite/include/Param.h
  sdks/cpp/lite/include/RangeConstraint.h
  sdks/cpp/lite/src/Param.cpp
  tools/codegen/cppgen.js
  tools/codegen/index.js
Labels: enhancement

#238 Replaced has_getStructInfo with C++20 concept
  sdks/cpp/lite/include/StructInfo.h
  sdks/cpp/lite/src/Param.cpp
Labels: enhancement

#245 Bug #235 ipr
  schema/catena.schema.json
  sdks/cpp/connections/gRPC/examples/status_update/device.status_update.json
Labels: bug
