Repository rossvideo/Catena, pull requests merged in 2025-06, with the labels that each got.

#724 Update to SocketReader and SocketWriter to fix parsing and support unary for streamed responses.
  interface/openapi/openapi.yaml
  sdks/cpp/connections/REST/include/SocketReader.h
  sdks/cpp/connections/REST/include/SocketWriter.h
  sdks/cpp/connections/REST/include/controllers/DeviceRequest.h
  sdks/cpp/connections/REST/include/interface/ISocketReader.h
  sdks/cpp/connections/REST/src/ServiceImpl.cpp
  sdks/cpp/connections/REST/src/SocketReader.cpp
  sdks/cpp/connections/REST/src/SocketWriter.cpp
  sdks/cpp/connections/REST/src/controllers/DeviceRequest.cpp
  sdks/cpp/connections/REST/tests/RESTMockClasses.h
  sdks/cpp/connections/REST/tests/SocketHelper.h
  sdks/cpp/connections/REST/tests/SocketReader_test.cpp
  sdks/cpp/connections/REST/tests/SocketWriter_test.cpp
Labels: ready for review

#737 Fixed a number of errors flagged when running examples using valgrind.
  sdks/cpp/connections/REST/examples/one_of_everything_REST/one_of_everything_REST.cpp
  sdks/cpp/connections/REST/examples/status_update_REST/status_update_REST.cpp
  sdks/cpp/connections/REST/examples/status_update_REST_JSON/status_update_REST_JSON.cpp
  sdks/cpp/connections/REST/examples/structs_with_authz_REST/structs_with_authz_REST.cpp
  sdks/cpp/connections/REST/examples/use_commands_REST/use_commands_REST.cpp
  sdks/cpp/connections/REST/examples/use_menus_REST/use_menus_REST.cpp
  sdks/cpp/connections/REST/include/controllers/Connect.h
  sdks/cpp/connections/REST/src/controllers/Connect.cpp
  sdks/cpp/connections/gRPC/examples/one_of_everything/one_of_everything.cpp
  sdks/cpp/connections/gRPC/examples/status_update/status_update.cpp
  sdks/cpp/connections/gRPC/examples/structs_with_authz/structs_with_authz.cpp
  sdks/cpp/connections/gRPC/examples/structs_with_authz_yaml/structs_with_authz_yaml.cpp
  sdks/cpp/connections/gRPC/examples/use_commands/use_commands.cpp
  sdks/cpp/connections/gRPC/examples/use_menus/use_menus.cpp
  sdks/cpp/connections/gRPC/include/CallData.h
  sdks/cpp/connections/gRPC/include/controllers/Connect.h
  sdks/cpp/connections/gRPC/src/ServiceImpl.cpp
  sdks/cpp/connections/gRPC/src/controllers/AddLanguage.cpp
  sdks/cpp/connections/gRPC/src/controllers/BasicParamInfoRequest.cpp
  sdks/cpp/connections/gRPC/src/controllers/Connect.cpp
  sdks/cpp/connections/gRPC/src/controllers/DeviceRequest.cpp
  sdks/cpp/connections/gRPC/src/controllers/ExecuteCommand.cpp
  sdks/cpp/connections/gRPC/src/controllers/ExternalObjectRequest.cpp
  sdks/cpp/connections/gRPC/src/controllers/GetParam.cpp
  sdks/cpp/connections/gRPC/src/controllers/GetPopulatedSlots.cpp
  sdks/cpp/connections/gRPC/src/controllers/GetValue.cpp
  sdks/cpp/connections/gRPC/src/controllers/LanguagePackRequest.cpp
  sdks/cpp/connections/gRPC/src/controllers/ListLanguages.cpp
  sdks/cpp/connections/gRPC/src/controllers/MultiSetValue.cpp
  sdks/cpp/connections/gRPC/src/controllers/UpdateSubscriptions.cpp
Labels: bug

#728 .proto changes to element_index and proceed flag
  docs/DevProcess.md
  docs/gRPC/Connect.md
  docs/gRPC/GetValue.md
  docs/gRPC/MultiSetValue.md
  docs/gRPC/SetValue.md
  interface/device.proto
  interface/param.proto
  sdks/cpp/common/include/IDevice.h
  sdks/cpp/common/include/rpc/Connect.h
  sdks/cpp/common/include/rpc/IConnect.h
  sdks/cpp/common/src/Device.cpp
  sdks/cpp/common/tests/CommonMockClasses.h
  sdks/cpp/common/tests/Connect_test.cpp
  sdks/cpp/connections/REST/examples/one_of_everything_REST/one_of_everything_REST.cpp
  sdks/cpp/connections/REST/examples/status_update_REST/status_update_REST.cpp
  sdks/cpp/connections/REST/examples/status_update_REST_JSON/status_update_REST_JSON.cpp
  sdks/cpp/connections/REST/examples/structs_with_authz_REST/structs_with_authz_REST.cpp
  sdks/cpp/connections/REST/examples/use_commands_REST/use_commands_REST.cpp
  sdks/cpp/connections/REST/examples/use_menus_REST/use_menus_REST.cpp
  sdks/cpp/connections/REST/src/controllers/Connect.cpp
  sdks/cpp/connections/REST/src/controllers/ExecuteCommand.cpp
  sdks/cpp/connections/REST/tests/ExecuteCommand_test.cpp
  sdks/cpp/connections/gRPC/examples/one_of_everything/one_of_everything.cpp
  sdks/cpp/connections/gRPC/examples/status_update/status_update.cpp
  sdks/cpp/connections/gRPC/examples/structs_with_authz/structs_with_authz.cpp
  sdks/cpp/connections/gRPC/examples/structs_with_authz_yaml/structs_with_authz_yaml.cpp
  sdks/cpp/connections/gRPC/examples/use_commands/use_commands.cpp
  sdks/cpp/connections/gRPC/examples/use_menus/use_menus.cpp
  sdks/cpp/connections/gRPC/src/controllers/Connect.cpp
  sdks/cpp/connections/gRPC/tests/ExecuteCommand_test.cpp
Labels: ready for review, Main Line, HIGH PRIORITY

#740 first commit
  sdks/go/README.md
Labels: documentation, Main Line

#723 REST Response Code and Endpoint Patch Job
  .vscode/tasks.json
  interface/openapi/openapi.yaml
  interface/openapi/paths/AddLanguage.yaml
  interface/openapi/paths/AssetRequest.yaml
  interface/openapi/paths/BasicParamInfoRequest.yaml
  interface/openapi/paths/BasicParamStream.yaml
  interface/openapi/paths/Command.yaml
  interface/openapi/paths/Connect.yaml
  interface/openapi/paths/Device.yaml
  interface/openapi/paths/DeviceRequest.yaml
  interface/openapi/paths/DeviceStream.yaml
  interface/openapi/paths/Devices.yaml
  interface/openapi/paths/ExecuteCommand.yaml
  interface/openapi/paths/GetParam.yaml
  interface/openapi/paths/GetPopulatedSlots.yaml
  interface/openapi/paths/GetValue.yaml
  interface/openapi/paths/LanguagePack.yaml
  interface/openapi/paths/LanguagePackRequest.yaml
  interface/openapi/paths/Languages.yaml
  interface/openapi/paths/ListLanguages.yaml
  interface/openapi/paths/MultiSetValue.yaml
  interface/openapi/paths/Param.yaml
  interface/openapi/paths/SetValue.yaml
  interface/openapi/paths/Subscriptions.yaml
  interface/openapi/paths/SubscriptionsStream.yaml
  interface/openapi/paths/UpdateSubscriptions.yaml
  interface/openapi/paths/Value.yaml
  interface/openapi/paths/Values.yaml
  sdks/cpp/common/src/Device.cpp
  sdks/cpp/connections/REST/src/controllers/AddLanguage.cpp
  sdks/cpp/connections/REST/src/controllers/AssetRequest.cpp
  sdks/cpp/connections/REST/src/controllers/BasicParamInfoRequest.cpp
  sdks/cpp/connections/REST/src/controllers/Connect.cpp
  sdks/cpp/connections/REST/src/controllers/DeviceRequest.cpp
  sdks/cpp/connections/REST/src/controllers/ExecuteCommand.cpp
  sdks/cpp/connections/REST/src/controllers/GetParam.cpp
  sdks/cpp/connections/REST/src/controllers/GetValue.cpp
  sdks/cpp/connections/REST/src/controllers/LanguagePackRequest.cpp
  sdks/cpp/connections/REST/src/controllers/ListLanguages.cpp
  unittests/cpp/REST/tests/AddLanguage_test.cpp
  unittests/cpp/REST/tests/BasicParamInfoRequest_test.cpp
  unittests/cpp/REST/tests/GetParam_test.cpp
  unittests/cpp/REST/tests/GetValue_test.cpp
  unittests/cpp/REST/tests/LanguagePackRequest_test.cpp
  unittests/cpp/REST/tests/ListLanguages_test.cpp
Labels: ready for review, Main Line

#765 Add compile commands to dev container build
  .devcontainer/devcontainer.dockerfile
Labels: hotfix

#781 Updated examples to use slot 0
  sdks/cpp/connections/REST/examples/CMakeLists.txt
  sdks/cpp/connections/REST/examples/api_only/CMakeLists.txt
  sdks/cpp/connections/REST/examples/api_only/api_only.cpp
  sdks/cpp/connections/REST/examples/asset_request_REST/device.asset_request.json
  sdks/cpp/connections/REST/examples/one_of_everything_REST/device.one_of_everything.yaml
  sdks/cpp/connections/REST/examples/status_update_REST/device.status_update.yaml
  sdks/cpp/connections/REST/examples/structs_with_authz_REST/device.AudioDeck.yaml
  sdks/cpp/connections/REST/examples/use_commands_REST/device.video_player.yaml
  sdks/cpp/connections/REST/examples/use_menus_REST/device.use_menus.yaml
  sdks/cpp/connections/gRPC/examples/external_object_request/device.external_object_request.json
  sdks/cpp/connections/gRPC/examples/one_of_everything/device.one_of_everything.yaml
  sdks/cpp/connections/gRPC/examples/status_update/device.status_update.json
  sdks/cpp/connections/gRPC/examples/structs_with_authz/device.AudioDeck.json
  sdks/cpp/connections/gRPC/examples/use_commands/device.video_player.json
  sdks/cpp/connections/gRPC/examples/use_menus/device.use_menus.json
Labels: ✅ ready for review
