Repository rossvideo/Catena, pull requests merged in 2025-08, with the labels that each got.

#893 Codegen now initialized parameters without a defined value
  tools/codegen/cpp/cppgen.js
  tools/codegen/cpp/param.js
Labels: ✅ ready for review

#932 Added JWS token expiration function to Authorizer
  sdks/cpp/common/include/Authorizer.h
  sdks/cpp/common/include/IAuthorizer.h
  sdks/cpp/common/src/Authorizer.cpp
  sdks/cpp/connections/REST/src/controllers/Connect.cpp
  sdks/cpp/connections/REST/src/controllers/ExecuteCommand.cpp
  sdks/cpp/connections/gRPC/include/controllers/ExecuteCommand.h
  sdks/cpp/connections/gRPC/src/controllers/Connect.cpp
  sdks/cpp/connections/gRPC/src/controllers/ExecuteCommand.cpp
  unittests/cpp/REST/tests/Connect_test.cpp
  unittests/cpp/REST/tests/ExecuteCommand_test.cpp
  unittests/cpp/common/CommonTestHelpers.h
  unittests/cpp/common/mocks/MockAuthorizer.h
  unittests/cpp/common/tests/Authorizer_test.cpp
  unittests/cpp/gRPC/tests/Connect_test.cpp
  unittests/cpp/gRPC/tests/ExecuteCommand_test.cpp
Labels: ✅ ready for review

#939 Add missing coverage for Device UT
  sdks/cpp/common/src/Device.cpp
  unittests/cpp/common/tests/Device_test.cpp
Labels: ✅ ready for review, ⏩ skip demo

#962 948 combined examples image
  .github/workflows/docker_builder.yml
  docker/example-entrypoint.sh
  docker/example-healthcheck.sh
  docker/example.dockerfile
Labels: ✅ ready for review

#961 Fixed protobuf serialization of STRING_CHOICE constraints
  sdks/cpp/common/CMakeLists.txt
  sdks/cpp/common/examples/use_constraints/use_constraints.cpp
  sdks/cpp/common/include/ChoiceConstraint.h
  sdks/cpp/common/src/ChoiceConstraint.cpp
  tools/codegen/cpp/constraint.js
  tools/codegen/cpp/cppgen.js
  unittests/cpp/common/CMakeLists.txt
  unittests/cpp/common/tests/ChoiceConstraint_test.cpp
  unittests/cpp/common/tests/RangeConstraint_test.cpp
Labels: 🐞 bug, ✅ ready for review

#972 953 code gen readonly bug
  sdks/cpp/connections/gRPC/examples/use_commands/device.video_player.json
  tools/codegen/cpp/param.js
Labels: 🐞 bug, ✅ ready for review

#986 better unit test context in workflow
  .github/workflows/cpp-pull-request.yml
Labels: ✅ ready for review

#992 rework unit test orgization
  .github/workflows/cpp-pull-request.yml
  .vscode/launch.json
  scripts/update_launch.sh
  unittests/cpp/REST/CMakeLists.txt
  unittests/cpp/common/CMakeLists.txt
  unittests/cpp/gRPC/CMakeLists.txt
Labels: ✅ ready for review
