Repository rossvideo/Catena, pull requests merged in 2025-07, with the labels that each got.

#806 Common Unit Tests - PolyglotText and Constraints
  sdks/cpp/common/CMakeLists.txt
  sdks/cpp/common/examples/use_constraints/use_constraints.cpp
  sdks/cpp/common/include/IConstraint.h
  sdks/cpp/common/include/IPolyglotText.h
  sdks/cpp/common/include/NamedChoiceConstraint.h
  sdks/cpp/common/include/PicklistConstraint.h
  sdks/cpp/common/include/PolyglotText.h
  sdks/cpp/common/include/RangeConstraint.h
  sdks/cpp/common/src/PicklistConstraint.cpp
  sdks/cpp/common/src/PolyglotText.cpp
  tools/codegen/cpp/constraint.js
  tools/codegen/cpp/cppgen.js
  unittests/cpp/common/CMakeLists.txt
  unittests/cpp/common/tests/NamedChoiceConstraint_test.cpp
  unittests/cpp/common/tests/PolyglotText_test.cpp
  unittests/cpp/common/tests/RangeConstraint_test.cpp
Labels: ✅ ready for review

#816 Fixed param json schema structField issue
  schema/catena.param_schema.json
  sdks/cpp/common/examples/import_params/device.import_params.json
  sdks/cpp/common/examples/import_params/params/param.city.json
  sdks/cpp/common/examples/import_params/params/param.location.json
  sdks/cpp/common/examples/import_params/params/param.ottawa.json
  sdks/cpp/common/examples/use_struct_arrays/device.AudioDeck.json
  sdks/cpp/common/examples/use_structs/device.use_structs.json
  sdks/cpp/common/examples/use_templates/device.use_templates.json
  sdks/cpp/common/examples/use_variants/device.use_variants.json
  sdks/cpp/connections/REST/examples/one_of_everything_REST/constraints/param.constraint_examples.yaml
  sdks/cpp/connections/REST/examples/one_of_everything_REST/device.one_of_everything.yaml
  sdks/cpp/connections/REST/examples/one_of_everything_REST/params/param.struct_array.yaml
  sdks/cpp/connections/REST/examples/one_of_everything_REST/params/param.struct_example.yaml
  sdks/cpp/connections/REST/examples/structs_with_authz_REST/device.AudioDeck.yaml
  sdks/cpp/connections/REST/examples/use_menus_REST/params/param.product.json
  sdks/cpp/connections/REST/src/ServiceImpl.cpp
  sdks/cpp/connections/gRPC/examples/one_of_everything/constraints/param.constraint_examples.yaml
  sdks/cpp/connections/gRPC/examples/one_of_everything/params/param.struct_array.yaml
  sdks/cpp/connections/gRPC/examples/one_of_everything/params/param.struct_example.yaml
  sdks/cpp/connections/gRPC/examples/structs_with_authz/device.AudioDeck.json
  sdks/cpp/connections/gRPC/examples/structs_with_authz_yaml/device.AudioDeck.yaml
  sdks/cpp/connections/gRPC/examples/use_menus/params/param.product.json
  tools/codegen/cpp/param.js
Labels: ✅ ready for review

#843 fix audio deck examples to have leading slash in subparams
  sdks/cpp/connections/REST/examples/structs_with_authz_REST/structs_with_authz_REST.cpp
  sdks/cpp/connections/gRPC/examples/structs_with_authz/structs_with_authz.cpp
  sdks/cpp/connections/gRPC/examples/structs_with_authz_yaml/structs_with_authz_yaml.cpp
Labels: 🛠️ hotfix

#811 Common Unit Tests - Path
  sdks/cpp/common/include/Path.h
  sdks/cpp/common/src/Path.cpp
  unittests/cpp/common/CMakeLists.txt
  unittests/cpp/common/tests/Path_test.cpp
Labels: ✅ ready for review, ⏩ skip demo

#842 Fixed connect REST tests
  unittests/cpp/REST/tests/Connect_test.cpp
Labels: 🛠️ hotfix, ✅ ready for review

#841 Perfected (Multi)SetValue
  .vscode/launch.json
  sdks/cpp/common/include/ParamWithValue.h
  sdks/cpp/common/include/StructInfo.h
  sdks/cpp/common/src/Device.cpp
  sdks/cpp/common/src/StructInfo.cpp
  unittests/cpp/common/tests/StructInfo_test.cpp
Labels: ✅ ready for review

#814 Subscription Manager Unit Test + Bug Fixes
  sdks/cpp/common/include/ParamVisitor.h
  sdks/cpp/common/src/ParamVisitor.cpp
  sdks/cpp/common/src/SubscriptionManager.cpp
  sdks/cpp/connections/REST/src/controllers/ParamInfoRequest.cpp
  sdks/cpp/connections/gRPC/src/controllers/ParamInfoRequest.cpp
  unittests/cpp/REST/RESTTestHelpers.h
  unittests/cpp/REST/tests/ParamInfoRequest_test.cpp
  unittests/cpp/common/CMakeLists.txt
  unittests/cpp/common/CommonTestHelpers.h
  unittests/cpp/common/tests/Connect_test.cpp
  unittests/cpp/common/tests/ParamVisitor_test.cpp
  unittests/cpp/common/tests/SubscriptionManager_test.cpp
  unittests/cpp/common/tests/subscription_manager_test.cpp
Labels: ✅ ready for review, ⏩ skip demo

#847 Refactor Unit Tests to use a Helper Function for Tokens
  unittests/cpp/REST/tests/Connect_test.cpp
  unittests/cpp/REST/tests/DeviceRequest_test.cpp
  unittests/cpp/REST/tests/ExecuteCommand_test.cpp
  unittests/cpp/REST/tests/GetParam_test.cpp
  unittests/cpp/REST/tests/GetValue_test.cpp
  unittests/cpp/REST/tests/LanguagePack_test.cpp
  unittests/cpp/REST/tests/MultiSetValue_test.cpp
  unittests/cpp/REST/tests/ParamInfoRequest_test.cpp
  unittests/cpp/REST/tests/Subscriptions_test.cpp
  unittests/cpp/common/CommonTestHelpers.h
  unittests/cpp/common/tests/Authorization_test.cpp
  unittests/cpp/common/tests/Connect_test.cpp
  unittests/cpp/common/tests/SubscriptionManager_test.cpp
  unittests/cpp/gRPC/CMakeLists.txt
  unittests/cpp/gRPC/tests/AddLanguage_test.cpp
  unittests/cpp/gRPC/tests/DeviceRequest_test.cpp
  unittests/cpp/gRPC/tests/ExecuteCommand_test.cpp
  unittests/cpp/gRPC/tests/GetParam_test.cpp
  unittests/cpp/gRPC/tests/GetValue_test.cpp
  unittests/cpp/gRPC/tests/MultiSetValue_test.cpp
Labels: ♻️ refactor

#850 Updated openAPI fqoid regex
  interface/openapi/paths/Value.yaml
  interface/openapi/paths/Values.yaml
  schema/catena.param_schema.json
Labels: 📃 documentation, 🔧 enhancement, ⏩ skip demo

#863 Authorizer updates and cleanup
  sdks/cpp/common/include/Authorization.h
  sdks/cpp/common/include/rpc/Connect.h
  sdks/cpp/common/src/Authorization.cpp
  sdks/cpp/common/src/Device.cpp
  sdks/cpp/connections/REST/src/controllers/AssetRequest.cpp
  unittests/cpp/common/tests/Authorization_test.cpp
Labels: ✅ ready for review

#879 fixed authorizer include path in Device_test
  unittests/cpp/common/tests/Device_test.cpp
Labels: 🛠️ hotfix

#870 Common Unit Tests - ParamDescriptor
  sdks/cpp/common/include/IParam.h
  sdks/cpp/common/include/IParamDescriptor.h
  sdks/cpp/common/include/ParamDescriptor.h
  sdks/cpp/common/include/ParamWithValue.h
  sdks/cpp/common/src/ParamDescriptor.cpp
  sdks/cpp/connections/REST/examples/one_of_everything_REST/one_of_everything_REST.cpp
  sdks/cpp/connections/REST/examples/use_commands_REST/use_commands_REST.cpp
  sdks/cpp/connections/gRPC/examples/one_of_everything/one_of_everything.cpp
  sdks/cpp/connections/gRPC/examples/use_commands/use_commands.cpp
  unittests/cpp/common/CMakeLists.txt
  unittests/cpp/common/mocks/MockParam.h
  unittests/cpp/common/mocks/MockParamDescriptor.h
  unittests/cpp/common/tests/ParamDescriptor_test.cpp
Labels: ✅ ready for review, ⏩ skip demo

#882 Default Max Connections CMake variables
  sdks/cpp/CMakeLists.txt
  sdks/cpp/common/src/SharedFlags.cpp
  sdks/cpp/connections/REST/include/ServiceImpl.h
  sdks/cpp/connections/gRPC/include/ServiceImpl.h
Labels: ✅ ready for review

#888 Fix clangd (and in effect Cursor)
  .vscode/settings.json
Labels: 🛠️ hotfix
