Repository rossvideo/Catena, pull requests merged in 2025-05, with the labels that each got.

#634 Add code coverage
  .devcontainer/devcontainer.dockerfile
  .devcontainer/toolchain-cpp.dockerfile
  .gitignore
  .vscode/tasks.json
  scripts/run_coverage.sh
  sdks/cpp/CMakeLists.txt
Labels: missing-jira, 5 min review

#639 Refactor mock classes
  sdks/cpp/common/tests/.gitignore
  sdks/cpp/common/tests/CMakeLists.txt
  sdks/cpp/common/tests/CommonMockClasses.h
  sdks/cpp/connections/REST/tests/CMakeLists.txt
  sdks/cpp/connections/REST/tests/GetValue_test.cpp
  sdks/cpp/connections/REST/tests/RESTMockClasses.h
Labels: missing-jira, 5 min review

#637 ListLangauge REST Unit tests
  sdks/cpp/connections/REST/src/controllers/ListLanguages.cpp
  sdks/cpp/connections/REST/tests/CMakeLists.txt
  sdks/cpp/connections/REST/tests/GetValue_test.cpp
  sdks/cpp/connections/REST/tests/ListLanguages_test.cpp
Labels: missing-jira, 10 min review

#638 LanguagePackRequest REST tests
  sdks/cpp/connections/REST/tests/CMakeLists.txt
  sdks/cpp/connections/REST/tests/LanguagePackRequest_test.cpp
Labels: missing-jira, 10 min review

#644 Update tasks.json to have coverage commands
  .vscode/tasks.json
Labels: 1 min review, missing-jira

#641 Subscription Manager Basic Unit Testing
  sdks/cpp/common/tests/CMakeLists.txt
  sdks/cpp/common/tests/CommonMockClasses.h
  sdks/cpp/common/tests/subscription_manager_test.cpp
Labels: missing-jira, 20 min review

#640 AddLanguage REST Unit Tests
  sdks/cpp/connections/REST/tests/AddLanguage_test.cpp
  sdks/cpp/connections/REST/tests/CMakeLists.txt
Labels: missing-jira, 20 min review

#642 Fixed SocketReader test coverage
  sdks/cpp/connections/REST/tests/SocketHelper.h
  sdks/cpp/connections/REST/tests/SocketReader_test.cpp
Labels: 1 min review, missing-jira

#646 MultiSetValue and SetValue REST Unit Tests
  sdks/cpp/connections/REST/src/controllers/MultiSetValue.cpp
  sdks/cpp/connections/REST/tests/CMakeLists.txt
  sdks/cpp/connections/REST/tests/MultiSetValue_test.cpp
  sdks/cpp/connections/REST/tests/SetValue_test.cpp
Labels: missing-jira, 30 min review

#647 Update tasks.json for coverage
  .vscode/tasks.json
Labels: 1 min review, missing-jira

#648 GetPopulatedSlots REST Unit Tests
  sdks/cpp/connections/REST/tests/CMakeLists.txt
  sdks/cpp/connections/REST/tests/GetPopulatedSlots_test.cpp
Labels: missing-jira, 10 min review
